# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/jisuanjizuchengyuanli/study/Analog_and_digital_circuit_experiment_improvement_class/labh6/labh6.srcs/sources_1/ip/VRAM_1/VRAM.xci
# IP: The module: 'VRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/jisuanjizuchengyuanli/study/Analog_and_digital_circuit_experiment_improvement_class/labh6/labh6.srcs/sources_1/ip/VRAM_1/VRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/jisuanjizuchengyuanli/study/Analog_and_digital_circuit_experiment_improvement_class/labh6/labh6.srcs/sources_1/ip/VRAM_1/VRAM.xci
# IP: The module: 'VRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/jisuanjizuchengyuanli/study/Analog_and_digital_circuit_experiment_improvement_class/labh6/labh6.srcs/sources_1/ip/VRAM_1/VRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
