# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cod_projects/Nexys4DDR_Master.xdc

# IP: ip/instrcution_memory/instrcution_memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==instrcution_memory || ORIG_REF_NAME==instrcution_memory} -quiet] -quiet
